// `import type` is erased at build time: it only brings in TypeScript types.
import type { Metadata, Viewport } from "next";

// next/font downloads Google Fonts AT BUILD TIME and self-hosts them,
// so there's no runtime request to Google and no flash of the wrong font
import { Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const sans = Plus_Jakarta_Sans({
  // Exposes the font as a CSS variable; globals.css maps it to Tailwind's font-sans.
  variable: "--font-sans-family",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// The browser tab title and search-engine description. Rename it on event day.
export const metadata: Metadata = {
  title: "BillSamaj: Your bill. Finally, understood.",
  description: "Upload a K-Electric, LESCO or IESCO electricity bill and get every charge explained in plain language.",
};

// Makes phones render at their real width instead of a zoomed-out desktop view.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

// Wraps EVERY page. `children` is the current page (like <Slot /> in Expo Router).
// LayoutProps is a global type generated by Next, so there's no import.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${sans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">{children}</body>
    </html>
  );
}
